# Schema for the configuration files of the layout custom style module.
layout_custom_style.settings:
  type: config_object
  label: 'layout custom style settings'
  mapping:
    example:
      type: string
      label: 'Example'
